### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by miTraPoNy** [corkami/mitra#4]
What is the problem please?

python mitra.py picture.jpg backdoor.zip
Traceback (most recent call last):
  File "mitra.py", line 3, in <module>
    from parsers import *
  File "/pentester/mitra-test/parsers/bpg.py", line 24, in <module>
    assert ue7_encs(127) == b"\x7f"
AssertionError

Thank you :-)

**Comment by GetRektBoy724** [comment]
i also get this

**Comment by ARitz-Cracker** [comment]
This is a python3 script. You're attempting to use python2
